name: mescal
dependencies:
  - python=3.10
  - numpy=1.23.5
  - pandas=1.5.2
  - matplotlib=3.6.2
  - astropy=5.1
  - openpyxl=3.0
  - joblib=1.1.1
  - rich=12.5
  - pip=23.0.1
  - pip:
      - lmfit==1.2.2